language: python
python: "3.6"

matrix:
  include:
    - name: "Format"
      before_install: pip install black
      install: skip
      script: black --check .
    - name: "Type checks"
      install: pip install .[dev]
      script: mypy --config-file=mypy.ini pyimagetest/
    - name: "Tests"
      before_install: pip install coverage codecov
      install: pip install .[dev]
      script: coverage run --rcfile=.coveragerc -m pytest test/
      after success: codecov

