language: python
python: "3.6"

matrix:
  include:
    - name: "Type checks"
      install: pip install .[type_check]
      script: mypy --config-file=mypy.ini pyimagetest/
    - name: "Tests"
      before_install: pip install coverage codecov
      install: pip install .[test]
      script: coverage run --rcfile=.coveragerc -m pytest test/
      after success: codecov

