language: python
python: "3.6"

matrix:
  include:
    - name: "Formatting"
      before_install: pip install black
      install: skip
      script: black --check .
    - name: "Tests w/o backends"
      before_install: pip install pytest
      install: pip install .
      script: pytest test
    - name: "Tests w/ backends"
      before_install: pip install pytest imageio pillow
      install: pip install .
      script: pytest test
